### ISSUE TITLE
Cannot select or tap a text due to a weird error

### ISSUE THREAD

**Issue by Inovvia** [ldi-github/shirates-core#115]
Here is the code snippet:
`it.select("BDO Unibank, Inc.").tap()`

Here is the error:
> 219	[00:01:14]	2024/09/19 10:36:37.119	{socialTestFunction-1}	0	-	[operate]	+2015	C	(tap)	Tap <BDO Unibank, Inc.>
> 220	[00:01:15]	2024/09/19 10:36:37.767	{socialTestFunction-1}	0	-	[info]	+648	C	(tap)	Syncing (1)
> 221	[00:01:15]	2024/09/19 10:36:37.877	{socialTestFunction-1}	0	-	[info]	+110	C	(tap)	Synced. (elapsed=0.11)
> 222	[00:01:15]	2024/09/19 10:36:37.890	{socialTestFunction-1}	0	-	[ERROR]	+13	C	()	For input string: "BDO Unibank, Inc."

Let me know if additional details are needed

**Comment by Inovvia** [comment]
Here are the logs and screenshot.

![223](https://github.com/user-attachments/assets/4e8b2928-dfaa-4490-94dd-37c8d6d38677)
[TestLog_20240919103522.log](https://github.com/user-attachments/files/17052821/TestLog_20240919103522.log)

**Comment by ldi-github** [comment]
Hi!
Can you attach the source xml file (*.xml)?

Or you can debug to find the cause of the problem.
Check following documents.

Watching sourceXML in file
https://ldi-github.github.io/shirates-core/in_action/debugging/watching_source_xml_in_file.html

Watching sourceXML in debugger
https://ldi-github.github.io/shirates-core/in_action/debugging/watching_source_xml_in_debugger.html

**Comment by Inovvia** [comment]
Sure here is the xml


`<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<hierarchy index="0" class="hierarchy" rotation="0" width="1344" height="2769">
  <android.widget.FrameLayout index="0" package="com.investagrams.investagrams.dev" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1344,2992]" displayed="true">
    <android.widget.LinearLayout index="0" package="com.investagrams.investagrams.dev" class="android.widget.LinearLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1344,2920]" displayed="true">
      <android.widget.FrameLayout index="0" package="com.investagrams.investagrams.dev" class="android.widget.FrameLayout" text="" resource-id="android:id/content" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,151][1344,2920]" displayed="true">
        <android.widget.FrameLayout index="0" package="com.investagrams.investagrams.dev" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,151][1344,2920]" displayed="true">
          <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,151][1344,2920]" displayed="true">
            <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,151][1344,2920]" displayed="true">
              <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,151][1344,339]" displayed="true">
                <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,206][150,281]" displayed="true">
                  <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[38,206][113,281]" displayed="true">
                    <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[38,206][113,281]" displayed="true">
                      <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[38,206][113,281]" displayed="true" />
                    </android.view.ViewGroup>
                  </android.view.ViewGroup>
                </android.view.ViewGroup>
                <android.widget.TextView index="1" package="com.investagrams.investagrams.dev" class="android.widget.TextView" text="Search" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[387,211][987,276]" displayed="true" />
              </android.view.ViewGroup>
              <android.view.ViewGroup index="1" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,339][1344,2920]" displayed="true">
                <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[36,375][1308,519]" displayed="true">
                  <android.widget.TextView index="0" package="com.investagrams.investagrams.dev" class="android.widget.TextView" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[51,409][153,485]" displayed="true" />
                  <android.widget.EditText index="1" package="com.investagrams.investagrams.dev" class="android.widget.EditText" text="Search stocks, currencies, and commodities" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="true" password="false" scrollable="false" selected="false" bounds="[153,390][1002,504]" displayed="true" hint="Search stocks, currencies, and commodities" />
                </android.view.ViewGroup>
                <android.view.ViewGroup index="1" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,555][1344,1005]" displayed="true">
                  <android.widget.ScrollView index="0" package="com.investagrams.investagrams.dev" class="android.widget.ScrollView" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,555][1299,960]" displayed="true">
                    <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,555][1299,960]" displayed="true">
                      <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,555][1299,690]" displayed="true">
                        <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,555][1299,690]" displayed="true">
                          <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,555][1299,675]" displayed="true">
                            <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,555][165,675]" displayed="true">
                              <android.widget.ImageView index="0" package="com.investagrams.investagrams.dev" class="android.widget.ImageView" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[75,585][135,645]" displayed="true" />
                            </android.view.ViewGroup>
                            <android.widget.TextView index="1" package="com.investagrams.investagrams.dev" class="android.widget.TextView" text="BDO " checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[165,583][405,648]" displayed="true" />
                            <android.widget.TextView index="2" package="com.investagrams.investagrams.dev" class="android.widget.TextView" text="BDO Unibank, Inc. " checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[405,583][1299,647]" displayed="true" />
                          </android.view.ViewGroup>
                        </android.view.ViewGroup>
                      </android.view.ViewGroup>
                      <android.view.ViewGroup index="1" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,690][1299,825]" displayed="true">
                        <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,690][1299,825]" displayed="true">
                          <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,690][1299,810]" displayed="true">
                            <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,690][165,810]" displayed="true">
                              <android.widget.ImageView index="0" package="com.investagrams.investagrams.dev" class="android.widget.ImageView" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[75,720][135,780]" displayed="true" />
                            </android.view.ViewGroup>
                            <android.widget.TextView index="1" package="com.investagrams.investagrams.dev" class="android.widget.TextView" text="BDORY " checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[165,718][405,783]" displayed="true" />
                            <android.widget.TextView index="2" package="com.investagrams.investagrams.dev" class="android.widget.TextView" text="Banco Do Brasil S.A. " checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[405,718][1299,782]" displayed="true" />
                          </android.view.ViewGroup>
                        </android.view.ViewGroup>
                      </android.view.ViewGroup>
                      <android.view.ViewGroup index="2" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,825][1299,960]" displayed="true">
                        <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,825][1299,960]" displayed="true">
                          <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,825][1299,945]" displayed="true">
                            <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,825][165,945]" displayed="true">
                              <android.widget.ImageView index="0" package="com.investagrams.investagrams.dev" class="android.widget.ImageView" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[75,855][135,915]" displayed="true" />
                            </android.view.ViewGroup>
                            <android.widget.TextView index="1" package="com.investagrams.investagrams.dev" class="android.widget.TextView" text="BDOUY " checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[165,853][405,918]" displayed="true" />
                            <android.widget.TextView index="2" package="com.investagrams.investagrams.dev" class="android.widget.TextView" text="BDO Unibank Inc " checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[405,853][1299,917]" displayed="true" />
                          </android.view.ViewGroup>
                        </android.view.ViewGroup>
                      </android.view.ViewGroup>
                    </android.view.ViewGroup>
                  </android.widget.ScrollView>
                </android.view.ViewGroup>
              </android.view.ViewGroup>
            </android.view.ViewGroup>
          </android.view.ViewGroup>
        </android.widget.FrameLayout>
      </android.widget.FrameLayout>
    </android.widget.LinearLayout>
    <android.view.View index="1" package="com.investagrams.investagrams.dev" class="android.view.View" text="" resource-id="android:id/navigationBarBackground" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,2920][1344,2992]" displayed="true" />
  </android.widget.FrameLayout>
</hierarchy>`

**Comment by ldi-github** [comment]
Thanks.

I found your UI contains text that has trailing space.

`text="BDO Unibank, Inc. "`

Try this.

`it.select("BDO Unibank, Inc. ").tap()`

or

`it.select("BDO Unibank, Inc.*").tap()`

**Comment by Inovvia** [comment]
It still errors out. I actually tried that earlier.

Error Log:
180	[00:00:50]	2024/09/19 13:16:51.146	{socialTestFunction-1}	0	-	[operate]	+2021	C	(tap)	Tap <BDO Unibank, Inc.*>
181	[00:00:51]	2024/09/19 13:16:51.911	{socialTestFunction-1}	0	-	[info]	+765	C	(tap)	Syncing (1)
182	[00:00:51]	2024/09/19 13:16:52.027	{socialTestFunction-1}	0	-	[info]	+116	C	(tap)	Synced. (elapsed=0.116)
183	[00:00:51]	2024/09/19 13:16:52.041	{socialTestFunction-1}	0	-	[ERROR]	+14	C	()	For input string: "BDO Unibank, Inc."
![image](https://github.com/user-attachments/assets/7a88c87b-1881-49ac-87cd-42307ff392f7)

**Comment by ldi-github** [comment]
I tried to reproduce the error with this sample code.
But could not.

`    val XML = """
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?> <hierarchy index="0" class="hierarchy" rotation="0" width="1344" height="2769"> <android.widget.FrameLayout index="0" package="com.investagrams.investagrams.dev" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1344,2992]" displayed="true"> <android.widget.LinearLayout index="0" package="com.investagrams.investagrams.dev" class="android.widget.LinearLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,0][1344,2920]" displayed="true"> <android.widget.FrameLayout index="0" package="com.investagrams.investagrams.dev" class="android.widget.FrameLayout" text="" resource-id="android:id/content" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,151][1344,2920]" displayed="true"> <android.widget.FrameLayout index="0" package="com.investagrams.investagrams.dev" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,151][1344,2920]" displayed="true"> <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,151][1344,2920]" displayed="true"> <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,151][1344,2920]" displayed="true"> <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,151][1344,339]" displayed="true"> <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,206][150,281]" displayed="true"> <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[38,206][113,281]" displayed="true"> <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[38,206][113,281]" displayed="true"> <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[38,206][113,281]" displayed="true" /> </android.view.ViewGroup> </android.view.ViewGroup> </android.view.ViewGroup> <android.widget.TextView index="1" package="com.investagrams.investagrams.dev" class="android.widget.TextView" text="Search" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[387,211][987,276]" displayed="true" /> </android.view.ViewGroup> <android.view.ViewGroup index="1" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,339][1344,2920]" displayed="true"> <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[36,375][1308,519]" displayed="true"> <android.widget.TextView index="0" package="com.investagrams.investagrams.dev" class="android.widget.TextView" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[51,409][153,485]" displayed="true" /> <android.widget.EditText index="1" package="com.investagrams.investagrams.dev" class="android.widget.EditText" text="Search stocks, currencies, and commodities" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="true" password="false" scrollable="false" selected="false" bounds="[153,390][1002,504]" displayed="true" hint="Search stocks, currencies, and commodities" /> </android.view.ViewGroup> <android.view.ViewGroup index="1" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,555][1344,1005]" displayed="true"> <android.widget.ScrollView index="0" package="com.investagrams.investagrams.dev" class="android.widget.ScrollView" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,555][1299,960]" displayed="true"> <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,555][1299,960]" displayed="true"> <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,555][1299,690]" displayed="true"> <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,555][1299,690]" displayed="true"> <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,555][1299,675]" displayed="true"> <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,555][165,675]" displayed="true"> <android.widget.ImageView index="0" package="com.investagrams.investagrams.dev" class="android.widget.ImageView" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[75,585][135,645]" displayed="true" /> </android.view.ViewGroup> <android.widget.TextView index="1" package="com.investagrams.investagrams.dev" class="android.widget.TextView" text="BDO " checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[165,583][405,648]" displayed="true" /> <android.widget.TextView index="2" package="com.investagrams.investagrams.dev" class="android.widget.TextView" text="BDO Unibank, Inc. " checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[405,583][1299,647]" displayed="true" /> </android.view.ViewGroup> </android.view.ViewGroup> </android.view.ViewGroup> <android.view.ViewGroup index="1" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,690][1299,825]" displayed="true"> <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,690][1299,825]" displayed="true"> <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,690][1299,810]" displayed="true"> <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,690][165,810]" displayed="true"> <android.widget.ImageView index="0" package="com.investagrams.investagrams.dev" class="android.widget.ImageView" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[75,720][135,780]" displayed="true" /> </android.view.ViewGroup> <android.widget.TextView index="1" package="com.investagrams.investagrams.dev" class="android.widget.TextView" text="BDORY " checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[165,718][405,783]" displayed="true" /> <android.widget.TextView index="2" package="com.investagrams.investagrams.dev" class="android.widget.TextView" text="Banco Do Brasil S.A. " checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[405,718][1299,782]" displayed="true" /> </android.view.ViewGroup> </android.view.ViewGroup> </android.view.ViewGroup> <android.view.ViewGroup index="2" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,825][1299,960]" displayed="true"> <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,825][1299,960]" displayed="true"> <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,825][1299,945]" displayed="true"> <android.view.ViewGroup index="0" package="com.investagrams.investagrams.dev" class="android.view.ViewGroup" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[45,825][165,945]" displayed="true"> <android.widget.ImageView index="0" package="com.investagrams.investagrams.dev" class="android.widget.ImageView" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[75,855][135,915]" displayed="true" /> </android.view.ViewGroup> <android.widget.TextView index="1" package="com.investagrams.investagrams.dev" class="android.widget.TextView" text="BDOUY " checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[165,853][405,918]" displayed="true" /> <android.widget.TextView index="2" package="com.investagrams.investagrams.dev" class="android.widget.TextView" text="BDO Unibank Inc " checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[405,853][1299,917]" displayed="true" /> </android.view.ViewGroup> </android.view.ViewGroup> </android.view.ViewGroup> </android.view.ViewGroup> </android.widget.ScrollView> </android.view.ViewGroup> </android.view.ViewGroup> </android.view.ViewGroup> </android.view.ViewGroup> </android.widget.FrameLayout> </android.widget.FrameLayout> </android.widget.LinearLayout> <android.view.View index="1" package="com.investagrams.investagrams.dev" class="android.view.View" text="" resource-id="android:id/navigationBarBackground" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,2920][1344,2992]" displayed="true" /> </android.widget.FrameLayout> </hierarchy>    """.trimIndent()

    @Test
    fun test1() {

        scenario {
            case(1) {
                TestElementCache.loadXml(XML)
                TestElementCache.synced = true
                it.select("BDO Unibank, Inc.*")
                    .tap()
            }
        }
    }
`

**Comment by ldi-github** [comment]
I would like to consider workaround.

How about followings?

`it.tap("BDO Unibank, Inc.")`

`it.tap("<BDO Unibank, Inc.>:left")`

**Comment by Inovvia** [comment]
Not sure what happened but your code worked! Thank you.

Would you be able to explain what "For input string" means?

**Comment by ldi-github** [comment]
That was good!

I think "For input string" is Java exception of parsing.

Example

```@Test
    fun test1() {

        scenario {
            case(1) {
                "A".toInt()
            }
        }
    }
```

```
java.lang.NumberFormatException: For input string: "A"

	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
...
```

I guess some error occurred in appium JavaClient
because your [TestLog_20240919103522.log](https://github.com/user-attachments/files/17052821/TestLog_20240919103522.log) has no stack trace information.

Check appiumYYYY-MM-DD_HHmmssfff.log
if some error occurred at that time.

**Comment by Inovvia** [comment]
I think I found the issue now. I had this code after tapping and I was indeed trying to convert to floor the price I get. I guess it was selecting the period in "BDO Unibank, Inc." 
```
val lastPrice = it.select("*.*")
            .getProperty("text")
```
