### ISSUE TITLE
Can't change device language in beforeAll

### ISSUE THREAD

**Issue by yukilabo** [ldi-github/shirates-core#29]
I want to change the language using LanguageHelperAndroid.setLanguage in beforeAll.
However, it fails because beforeAll is called before Appium initialization.

Is it possible to move the code block

https://github.com/ldi-github/shirates-core/blob/main/src/main/kotlin/shirates/core/testcode/UITestCallbackExtension.kt#L128-L132

to

https://github.com/ldi-github/shirates-core/blob/main/src/main/kotlin/shirates/core/testcode/UITestCallbackExtension.kt#L177

**Comment by ldi-github** [comment]
Hi @yukilabo . Thank you for your feedback!

We implemented new function` beforeAllAfterSetup` in version 4.1.0.
https://github.com/ldi-github/shirates-core/blob/main/doc/markdown/in_action/test_fixture/test_fixture.md

Try it!
I hope you enjoy your auto testing with Shirates.
