### ISSUE TITLE
Sync keeps timing out

### ISSUE THREAD

**Issue by Inovvia** [ldi-github/shirates-core#74]
My test yesterday were working fine however I'm not sure why my tests are running slowly today. I even tried reinstalling appium.

(syncCache)	Synchronization timed out (elapsed=82.954 > syncWaitSeconds=60.0, currentScreen=?)

**Comment by Inovvia** [comment]
NVM I was able to fix this. To anyone that experience this make sure that your app is idle (no animations)

**Comment by ldi-github** [comment]
Thank you for your feedback and enjoy testing with Shirates.

Check parameters for emulator/simulator. ( https://ldi-github.github.io/shirates-core/basic/parameter/parameters.html )
For other performance problem, see also Tutorial(In action).

**Comment by ldi-github** [comment]
Thank you for your feedback.

If your app has loop animation, syncing cache never finishes.
In this case, consider setting enableAutoSyncAndroid/enableAutoSyncIos to false.
